### ISSUE TITLE
Tracing is not enabled in debug builds

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/ethos#63]
In a debug build:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug
make VERBOSE=1
```
I see these compiler options:
```
-DETHOS_ASSERTIONS -DETHOS_DEBUG -DETHOS_TRACING 
```

But they have no effect. The source code uses `EO_TRACING` and `EO_ASSERTION` instead. and there's no 
`DEBUG`  anywhere in the source.

I'm on commit 9b2fd9beb30ebdc3ca481c93e89b5a6e99d2b523.

**Comment by ajreynol** [comment]
This is fixed by https://github.com/cvc5/ethos/pull/62.
