### ISSUE TITLE
Segmentation fault while checking a certificate

### ISSUE THREAD

**Issue by Mallku2** [cvc5/ethos#98]
For the following proof certificate (reduced from another) I am getting a `Segmentation fault` error, without further useful information to troubleshoot the issue. Would it be possible to capture the erroneous situation and provide the user with some information about it?

```
(program check_bind ((ctx Bool) (T Type) (l T) (r T) (l1 T) (r1 T))
  (Bool T T T T) Bool
  (
   ((check_bind ctx l r l1 r1) true)
  )
)

(declare-rule bind ((ctx Bool) (old_ctx Bool) (T Type) (l T) (r T) (l1 T) (r1 T))
  :assumption ctx
  :conclusion-given
)

(declare-const @cl (-> Bool Bool Bool) :right-assoc-nil false)

(define ctx1 ( ) true)
(assume-push context ctx1)
(assume-push context true)
(step-pop t5.t4 (@cl true) :rule bind)
```

**Comment by ajreynol** [comment]
Hm, I am not getting this behavior, I get:
```
ajreynol@r-lnx201105[~/ethos/tests]% ethos segfault-98.eo 
Including file segfault-98.eo did not preserve assumption scope
```
What was the name of this file?  Wondering if it was related to this recent fix: https://github.com/cvc5/ethos/pull/99
